apiVersion: v1
kind: ServiceAccount
metadata:
  name: agent-operator
  namespace: agent-env
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: manage-agent-pods
  namespace: agent-env
rules:
- apiGroups: ["", "apps"]
  resources: ["deployments", "services", "pods", "configmaps", "secrets", "endpoints"]
  verbs: ["get", "list", "create", "patch", "update", "delete", "watch"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: bind-agent-operator
  namespace: agent-env
subjects:
- kind: ServiceAccount
  name: agent-operator
roleRef:
  kind: Role
  name: manage-agent-pods
  apiGroup: rbac.authorization.k8s.io